$files=diplo.c demographie.c perso.c net.c utile.c inventaire.c map_op.c req.c deschiffrement.c acount.c

all:
	gcc -g main.c diplo.c demographie.c perso.c net.c utile.c inventaire.c map_op.c req.c deschiffrement.c acount.c -o serveur

land:
	gcc -g generate_land.c -o land
